before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: dirhttps
    ldflags:
      - -s -w -X github.com/maetthu/dirhttps/internal/lib/version.Version={{.Version}} -X github.com/maetthu/dirhttps/internal/lib/version.Commit={{.Commit}} -X github.com/maetthu/dirhttps/internal/lib/version.Date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - files:
      - LICENSE
      - README.md

